version: "3.7"

services:
    telegram-bot-api:
        image: aiogram/telegram-bot-api:latest
        environment:
            TELEGRAM_API_ID: "${TELEGRAM_API_ID}"
            TELEGRAM_API_HASH: "${TELEGRAM_API_HASH}"
            TELEGRAM_LOCAL: "${TELEGRAM_LOCAL}"
        volumes:
            - ./bot-api:/var/lib/telegram-bot-api
        ports:
            - 8081:8081
